import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const environmentKeys = [
  'SAMPLE_DATAKIT_URL',
  'SAMPLE_DATAWAY_URL',
  'SAMPLE_CLIENT_TOKEN',
  'SAMPLE_ANDROID_APP_ID',
  'SAMPLE_IOS_APP_ID',
  'SAMPLE_SERVICE_NAME',
  'SAMPLE_ENV',
  'SAMPLE_DEBUG',
];

const outputRoot = path.resolve(readOption('--output-root') || process.cwd());
const configuration = readConfiguration(process.env);
const source = renderConfiguration(configuration);
const targets = [
  'examples/creator2/SampleEnvironment.generated.ts',
  'examples/creator3/SampleEnvironment.generated.ts',
  'examples/creator2-app/assets/Script/SampleEnvironment.generated.ts',
];

await Promise.all(targets.map(async (target) => {
  const destination = path.join(outputRoot, target);
  await mkdir(path.dirname(destination), { recursive: true });
  await writeFile(destination, source);
}));

process.stdout.write(`Generated ${targets.length} ignored Sample configuration files from environment variables.\n`);

function readConfiguration(environment) {
  const values = Object.fromEntries(environmentKeys.map((key) => [key, optional(environment[key])]));
  const datakitUrl = values.SAMPLE_DATAKIT_URL;
  const datawayUrl = values.SAMPLE_DATAWAY_URL;
  const clientToken = values.SAMPLE_CLIENT_TOKEN;

  if (datakitUrl && (datawayUrl || clientToken)) {
    fail('Set SAMPLE_DATAKIT_URL or SAMPLE_DATAWAY_URL with SAMPLE_CLIENT_TOKEN, not both.');
  }
  if (!datakitUrl && !(datawayUrl && clientToken)) {
    fail('Set SAMPLE_DATAKIT_URL or both SAMPLE_DATAWAY_URL and SAMPLE_CLIENT_TOKEN.');
  }
  if (Boolean(datawayUrl) !== Boolean(clientToken)) {
    fail('SAMPLE_DATAWAY_URL and SAMPLE_CLIENT_TOKEN must be set together.');
  }

  const androidAppId = values.SAMPLE_ANDROID_APP_ID;
  const iosAppId = values.SAMPLE_IOS_APP_ID;
  if (!androidAppId && !iosAppId) {
    fail('Set SAMPLE_ANDROID_APP_ID, SAMPLE_IOS_APP_ID, or both.');
  }

  return {
    sdk: {
      ...(datakitUrl ? { datakitUrl } : { datawayUrl, clientToken }),
      debug: parseBoolean(values.SAMPLE_DEBUG, true),
      serviceName: values.SAMPLE_SERVICE_NAME || 'cocos-diagnostic-game',
      env: values.SAMPLE_ENV || 'demo',
    },
    rum: {
      ...(androidAppId ? { androidAppId } : {}),
      ...(iosAppId ? { iosAppId } : {}),
    },
  };
}

function renderConfiguration(configuration) {
  return [
    '// Generated by npm run sample:configure. Contains local credentials; do not commit.',
    `export const sampleEnvironment = ${JSON.stringify(configuration, null, 2)};`,
    '',
  ].join('\n');
}

function readOption(name) {
  const argumentsList = process.argv.slice(2);
  const exactIndex = argumentsList.indexOf(name);
  if (exactIndex >= 0) {
    const value = argumentsList[exactIndex + 1];
    if (!value || value.startsWith('--')) fail(`Missing value for ${name}.`);
    return value;
  }
  const prefix = `${name}=`;
  const inline = argumentsList.find((argument) => argument.startsWith(prefix));
  return inline ? inline.slice(prefix.length) : undefined;
}

function optional(value) {
  return typeof value === 'string' && value.trim() ? value.trim() : undefined;
}

function parseBoolean(value, fallback) {
  if (value === undefined) return fallback;
  if (value === 'true') return true;
  if (value === 'false') return false;
  fail('SAMPLE_DEBUG must be true or false.');
}

function fail(message) {
  process.stderr.write(`[cocos-sdk-sample] ${message}\n`);
  process.exit(1);
}
